Books/Models/Book.cs
using Microsoft.AspNetCore.Mvc.ViewEngines;
using System.ComponentModel.DataAnnotations;

namespace Books.Models
{
    public class Book
    {
        public int Id { get; set; }

        [StringLength(100)]
        [Required]
        public string Title { get; set; }

        [Display(Name = "Year Published")]
        [Required]
        public int? YearPublished { get; set; }

        [Display(Name = "Number of pages")]
        [Required]
        public int? NumPages { get; set; }

        [StringLength(int.MaxValue)]
        public string? Description { get; set; }

        [StringLength(50)]
        public string? Publisher { get; set; }

        [StringLength(int.MaxValue)]
        public string? FrontPage { get; set; }

        [StringLength(int.MaxValue)]
        [Display(Name = "Download link")]
        public string? DownloadUrl { get; set; }

        public Author? Author { get; set; }

        [Display(Name = "Author")]
        public int AuthorId { get; set; }

        public ICollection<BookGenre>? Genres { get; set; }

        public ICollection<Review>? Reviews { get; set; }

        public ICollection<UserBooks>? Users { get; set; }

        [Display(Name = "Average Rating")]
        public double AverageRating()
        {
            if (Reviews != null && Reviews.Any() && Reviews.All(r => r.Rating != null))
            {
                int Rating = (int)Reviews.Sum(r => r.Rating);
                return (double)Rating / Reviews.Count;
            }

            return 0;
        }
    }
}

Books/Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Books.Models;
using Books.Data;
using Books.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Books.Areas.Identity.Data;
using Microsoft.AspNetCore.Identity;

namespace Books.Controllers
{
    public class BooksController : Controller
    {
        private readonly BooksContext _context;
        private readonly UserManager<BooksUser> _userManager;


        public BooksController(BooksContext context, UserManager<BooksUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Books
        public async Task<IActionResult> Index(string searchFunction)
        {
            IQueryable<Book> books = _context.Book
                .Include(b => b.Author)
                .Include(b => b.Genres)
                .ThenInclude(bg => bg.Genre)
                .Include(b => b.Reviews);
            IQueryable<string> titleQuery = _context.Book
                .OrderBy(b => b.Title)
                .Select(b => b.Title)
                .Distinct();

            if (!string.IsNullOrEmpty(searchFunction))
            {
                books = books.Where(b =>
                b.Title.Contains(searchFunction) ||
                b.Author.FirstName.Contains(searchFunction) ||
                b.Author.LastName.Contains(searchFunction) ||
                b.Genres.Any(b => b.Genre.GenreName.Contains(searchFunction)
                ));
            }

            foreach (var book in books)
            {
                var distinctGenres = book.Genres
                    .Where(bg => bg.Genre != null)
                    .GroupBy(bg => bg.GenreId)
                    .Select(group => group.First())
                    .ToList();

                book.Genres = distinctGenres;
            }

            var bookViewModel = new BookFilterViewModel
            {
                CurrentBooks = await books.ToListAsync(),
                FilterOptions = new SelectList(await titleQuery.ToListAsync())
            };

            return View(bookViewModel);
        }

        // GET: Books/Details/5
        [Authorize(Roles = "User")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = await _context.Book
                .Include(b => b.Author)
                .Include(b => b.Genres)
                .ThenInclude(b => b.Genre)
                .Distinct()
                .Include(b => b.Reviews)
                .FirstOrDefaultAsync(b => b.Id == id);

            if (book == null)
            {
                return NotFound();
            }

            string purchased = "No";
            var usr = await _userManager.GetUserAsync(HttpContext.User);
            if (usr != null)
            {
                var isPurchased = await _context.UserBooks.Where(b => b.BookId == id && b.AppUser == usr.Email).FirstOrDefaultAsync();
                if (isPurchased != null)
                {
                    purchased = "Yes";
                }
                ViewBag.Email = usr.Email;
            }
            else
            {
                ViewBag.Email = null;
            }
            // Get the reviews of this book
            var all_review = await _context.Review.Where(b => b.BookId == id).ToListAsync();

            var bookDetailsVM = new BookDetails
            {
                Book = book,
                Reviews = all_review,
                Purchased = purchased
            };

            return View(bookDetailsVM);
        }

        // GET: Books/Create
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create()
        {
            ViewBag.Genres = new MultiSelectList(await _context.Genre.ToListAsync(), "Id", "GenreName");
            ViewBag.AuthorId = new SelectList(await _context.Author.ToListAsync(), "Id", "FullName");
            return View();
        }

        // POST: Books/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create([Bind("Id,Title,YearPublished,NumPages,Description,Publisher,FrontPage,DownloadUrl,AuthorId")] Book book, int[] selectedGenres)
        {
            if (ModelState.IsValid)
            {
                _context.Add(book);
                await _context.SaveChangesAsync();

                if (selectedGenres != null)
                {
                    foreach (var genreId in selectedGenres)
                    {
                        _context.Add(new BookGenre { BookId = book.Id, GenreId = genreId });
                    }
                    await _context.SaveChangesAsync();
                }

                return RedirectToAction(nameof(Index));
            }

            ViewBag.AuthorId = new SelectList(await _context.Author.ToListAsync(), "Id", "FullName", book.AuthorId);
            ViewBag.Genres = new MultiSelectList(await _context.Genre.ToListAsync(), "Id", "GenreName", selectedGenres);

            return View(book);
        }

        // GET: Books/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = await _context.Book
                .Include(b => b.Genres)
                .FirstOrDefaultAsync(b => b.Id == id);

            if (book == null)
            {
                return NotFound();
            }

            var selectedGenreIds = book.Genres.Select(bg => bg.GenreId).ToList();

            ViewBag.AuthorId = new SelectList(await _context.Author.ToListAsync(), "Id", "FullName", book.AuthorId);
            ViewBag.Genres = new SelectList(await _context.Genre.ToListAsync(), "Id", "GenreName", book.Genres.Select(bg => bg.GenreId));
            ViewBag.SelectedGenres = selectedGenreIds;
            return View(book);
        }

        // POST: Books/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,YearPublished,NumPages,Description,Publisher,FrontPage,DownloadUrl,AuthorId")] Book book, int[] selectedGenres)
        {
            if (id != book.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(book);

                    var existingGenres = _context.BookGenre.Where(bg => bg.BookId == id);
                    _context.BookGenre.RemoveRange(existingGenres);

                    if (selectedGenres != null)
                    {
                        foreach (var genreId in selectedGenres)
                        {
                            _context.Add(new BookGenre { BookId = book.Id, GenreId = genreId });
                        }
                    }

                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BookExists(book.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }

            ViewBag.Genres = new MultiSelectList(await _context.Genre.ToListAsync(), "Id", "GenreName", selectedGenres);
            ViewBag.AuthorId = new SelectList(_context.Author, "Id", "FullName", book.AuthorId);
            return View(book);
        }

        // GET: Books/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = await _context.Book
                .Include(b => b.Author)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }

        // POST: Books/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var book = await _context.Book.FindAsync(id);
            if (book != null)
            {
                _context.Book.Remove(book);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        [Authorize(Roles = "User")]
        public async Task<IActionResult> MyBooks(string searchString)
        {
            var usr = await _userManager.GetUserAsync(HttpContext.User);
            IQueryable<UserBooks> books = _context.UserBooks.AsQueryable().Where(s => s.AppUser == usr.Email);
            IQueryable<string> genreQuery = _context.Genre.Distinct().Select(g => g.GenreName).Distinct();
            if (!string.IsNullOrEmpty(searchString))
            {
                books = books.Where(s => s.Book.Title.Contains(searchString));
            }

            books = books.Include(b => b.Book).ThenInclude(b => b.Author);

            var bookGenreVM = new BookGenreViewModel
            {

Books/Controllers/ReviewsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Books.Models;
using Books.Data;
using Microsoft.AspNetCore.Authorization;

namespace Books.Controllers
{
    public class ReviewsController : Controller
    {
        private readonly BooksContext _context;

        public ReviewsController(BooksContext context)
        {
            _context = context;
        }

        // GET: Reviews
        public async Task<IActionResult> Index()
        {
            var booksContext = _context.Review.Include(r => r.Book);
            return View(await booksContext.ToListAsync());
        }

        // GET: Reviews/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var review = await _context.Review
                .Include(r => r.Book)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (review == null)
            {
                return NotFound();
            }

            return View(review);
        }

        // GET: Reviews/Create
        [Authorize(Roles = "User")]
        public IActionResult Create()
        {
            ViewData["BookId"] = new SelectList(_context.Book, "Id", "Title");
            return View();
        }

        // POST: Reviews/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "User")]
        public async Task<IActionResult> Create([Bind("Id,BookId,AppUser,Comment,Rating")] Review review)
        {
            if (ModelState.IsValid)
            {
                _context.Add(review);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["BookId"] = new SelectList(_context.Book, "Id", "Title", review.BookId);
            return View(review);
        }

        // GET: Reviews/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var review = await _context.Review.FindAsync(id);
            if (review == null)
            {
                return NotFound();
            }
            ViewData["BookId"] = new SelectList(_context.Book, "Id", "Title", review.BookId);
            return View(review);
        }

        // POST: Reviews/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,BookId,AppUser,Comment,Rating")] Review review)
        {
            if (id != review.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(review);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ReviewExists(review.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["BookId"] = new SelectList(_context.Book, "Id", "Title", review.BookId);
            return View(review);
        }

        // GET: Reviews/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var review = await _context.Review
                .Include(r => r.Book)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (review == null)
            {
                return NotFound();
            }

            return View(review);
        }

        // POST: Reviews/Delete/5
        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var review = await _context.Review.FindAsync(id);
            if (review != null)
            {
                _context.Review.Remove(review);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ReviewExists(int id)
        {
            return _context.Review.Any(e => e.Id == id);
        }
    }
}

Books/Views/Books/Create.cshtml
@model Books.Models.Book

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Book</h4>
<hr />

<style>
    body {
        background-image: linear-gradient(to right, #ffec7a, #f2b93a);
    }
</style>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="YearPublished" class="control-label"></label>
                <input asp-for="YearPublished" class="form-control" />
                <span asp-validation-for="YearPublished" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumPages" class="control-label"></label>
                <input asp-for="NumPages" class="form-control" />
                <span asp-validation-for="NumPages" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Publisher" class="control-label"></label>
                <input asp-for="Publisher" class="form-control" />
                <span asp-validation-for="Publisher" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FrontPage" class="control-label"></label>
                <input asp-for="FrontPage" class="form-control" />
                <span asp-validation-for="FrontPage" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DownloadUrl" class="control-label"></label>
                <input asp-for="DownloadUrl" class="form-control" />
                <span asp-validation-for="DownloadUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AuthorId" class="control-label"></label>
                <select asp-for="AuthorId" class ="form-control" asp-items="ViewBag.AuthorId"></select>
            </div>
            <div class="form-group">
                <label asp-for="Genres">Genres: </label>
                <div>
                    @foreach (var genre in ViewBag.Genres)
                    {
                        <div class="form-check">
                            @{
                                int genreId = (int.Parse(genre.Value));
                                bool isChecked = (ViewBag.SelectedGenres as List<int>)?.Contains(genreId) ?? false;
                            }
                            <input type="checkbox" class="form-check-input" name="selectedGenres" value="@genre.Value" id="@genre.Value"
                            @(isChecked ? "checked" : "") /> @genre.Text
                        </div>
                    }
                </div>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Books/Views/Books/Details.cshtml
@model Books.ViewModels.BookDetails

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<style>
    body {
        background-image: linear-gradient(to right, #ffec7a, #f2b93a);
    }
</style>

<div>
    <h4>Book</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Book.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Book.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Book.YearPublished)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Book.YearPublished)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Book.NumPages)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Book.NumPages)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Book.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Book.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Book.Publisher)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Book.Publisher)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Book.FrontPage)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Book.FrontPage)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Book.DownloadUrl)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Book.DownloadUrl)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Book.Author)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Book.Author.FullName)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Book.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>
<div>
    @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
    {
        <p><a asp-action="Edit" asp-route-id="@Model?.Book.Id">Edit</a>|</p>
    }
    @if (Model.Purchased == "Yes")
    {
        <a asp-controller="Reviews" asp-action="Create" asp-route-id="@Model?.Book.Id">Add review</a>
    }
</div>

Books/Views/Books/Index.cshtml
@model Books.ViewModels.BookFilterViewModel

@{
    ViewData["Title"] = "Index";
}

<h1>GoodReads</h1>

<style>
    body {
        background-image: linear-gradient(to right, #ffec7a, #f2b93a);
    }

    img {
        max-height: 300px;
        max-width: 300px;
        height: auto;
        width: auto;
    }

    h1 {
        color: dodgerblue;
    }

    .title {
        font-size: 20px;
    }

    table {
        background-color: white;
        border-radius: 7px;
        box-shadow: 3px 3px 3px #999;
    }

    .form-control {
        box-shadow: 1px 1px 1px #999;
    }

    footer {
        background-color: white;
    }
</style>

@if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
{
    <p>
        <a asp-action="Create">Create New</a>
    </p>
}


<form asp-controller="Books" asp-action="Index" method="get">
    <div class="row">
        <div class="col-md-8">
            <input type="text" asp-for="SearchFunction" class="form-control" placeholder="Search by title, author, or genre..." />
        </div>
        <div class="col-md-4">
            <input type="submit" value="Filter" class="btn btn-primary" />
        </div>
    </div>
</form>

<br />

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.CurrentBooks[0].Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CurrentBooks[0].Author.FullName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CurrentBooks[0].YearPublished)
            </th>
            <th>
                Genres
            </th>
            <th>
                Average Rating
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CurrentBooks[0].FrontPage)
            </th>
        </tr>
    </thead>
    <tbody>
        @if (Model.CurrentBooks != null)
        {
            @foreach (var item in Model.CurrentBooks)
            {
                <tr class="hoverable-row" onmouseover="this.classList.add('selected')" onmouseout="this.classList.remove('selected')">
                    <td class="title">
                        @Html.DisplayFor(modelItem => item.Title)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Author.FullName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.YearPublished)
                    </td>
                    <td>
                        @if (item.Genres != null && item.Genres.Any())
                        {
                            <ul>
                                @foreach (var genre in item.Genres)
                                {
                                    <li>@genre.Genre.GenreName</li>
                                }
                            </ul>
                        }
                        else
                        {
                            <span>No genres available</span>
                        }
                    </td>
                    <td>
                        @item.AverageRating()
                    </td>
                    <td>
                        @if (!string.IsNullOrEmpty(item.FrontPage))
                        {
                            <img src="@item.FrontPage" alt="Book Cover" />
                        }
                        else
                        {
                            <p>No image available.</p>
                        }
                    </td>
                    <td>
                        @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                        {
                            <a asp-action="Edit" asp-route-id="@item.Id">Edit</a>
                        } |
                        <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                        @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                        {
                            <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                        }
                        @if (User.Identity.IsAuthenticated && User.IsInRole("User"))
                        {
                            <form method="post" asp-controller="Books" asp-action="Buy" asp-route-id="@item.Id">
                                <button type="submit" class="btn btn-link">Buy</button>
                            </form>
                        }
                    </td>
                </tr>
            }
        }
    </tbody>
</table>

Books/Views/Books/MyBooks.cshtml
@model Books.ViewModels.BookGenreViewModel

@{
    ViewData["Title"] = "My Reads";
}

<h1>My Reads</h1>

<style>
    body {
        background-image: linear-gradient(to right, #ffec7a, #f2b93a);
    }

    img {
        max-height: 300px;
        max-width: 300px;
        height: auto;
        width: auto;
    }

    h1 {
        color: dodgerblue;
    }

    .title {
        font-size: 20px;
    }

    table {
        background-color: white;
        border-radius: 7px;
        box-shadow: 3px 3px 3px #999;
    }

    .form-control {
        box-shadow: 1px 1px 1px #999;
    }

    footer {
        background-color: white;
    }
</style>

<form asp-controller="Books" asp-action="MyBooks" method="get">
    <p>
        <div>
            <input type="text" asp-for="SearchFunction" class="form-control" placeholder="Search by title, author, or genre..." />
        </div>
        <div>
            <input type="submit" value="Filter" class="btn btn-primary" />
        </div>
    </p>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Books[0].Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Books[0].Author.FullName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Books[0].YearPublished)
            </th>
            <th>
                Genres
            </th>
            <th>
                Average Rating
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Books[0].FrontPage)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Books)
        {
            <tr class="hoverable-row" onmouseover="this.classList.add('selected')" onmouseout="this.classList.remove('selected')">
                <td class="title">
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Author.FullName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.YearPublished)
                </td>
                <td>
                    @if (item.Genres != null && item.Genres.Any())
                    {
                        <ul>
                            @foreach (var genre in item.Genres)
                            {
                                <li>@genre.Genre.GenreName</li>
                            }
                        </ul>
                    }
                    else
                    {
                        <span>No genres available</span>
                    }
                </td>
                <td>
                    @item.AverageRating()
                </td>
                <td>
                    @if (!string.IsNullOrEmpty(item.FrontPage))
                    {
                        <img src="@item.FrontPage" alt="Book Cover" />
                    }
                    else
                    {
                        <p>No image available.</p>
                    }
                </td>
                <td>
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    @if (User.Identity.IsAuthenticated && User.IsInRole("User"))
                    {
                        <a asp-action="ReturnBook" asp-route-id="@item.Id">Return</a>
                    }
                </td>
            </tr>
        }
    </tbody>
</table>